/**
 * Mapbox Static Images API URLs for neighborhood map previews.
 *
 * These URLs are loaded directly by the browser (not through Next's image
 * optimizer): the Mapbox token is URL-restricted, so requests succeed only
 * when they carry the site's Referer — which browser <img> fetches do (same
 * mechanism mapbox-gl tile requests already rely on) and server-side
 * optimizer fetches do not. Keep these images `unoptimized` and never use
 * them as og:image (social crawlers send no Referer).
 *
 * The style is generated by scripts/generate-static-map-style.ts (the
 * satellite-streets variant: imagery + the site's zoning fills) and uploaded
 * to Mapbox Studio — the zoning overlay can't be injected per-request via
 * `addlayer` because the static renderer's internal fetch of the private
 * zoning tileset drops the Referer and gets 403'd. If the zoning legend
 * changes, re-run the script, re-upload, and update STATIC_MAP_STYLE.
 */
const STATIC_MAP_STYLE = 'dwahbe/cmq9vnkp4002901qz8bk094jy';
/** Light-basemap variant (unused by the previews, published alongside the
 * satellite style): dwahbe/cmq9vmz4w002l01qzbionfrik */

export const STATIC_MAP_WIDTH = 800;
export const STATIC_MAP_HEIGHT = 500;

export interface StaticMapOptions {
  width?: number;
  height?: number;
  /** Defaults to NEXT_PUBLIC_MAPBOX_TOKEN. */
  token?: string;
}

/** Static map image URL fitted to the given [west, south, east, north] bounds. */
export function staticMapUrl(
  bounds: [number, number, number, number],
  options: StaticMapOptions = {}
): string | null {
  const token = options.token ?? process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
  if (!token) return null;

  const width = options.width ?? STATIC_MAP_WIDTH;
  const height = options.height ?? STATIC_MAP_HEIGHT;
  const bbox = `[${bounds.join(',')}]`;

  return (
    `https://api.mapbox.com/styles/v1/${STATIC_MAP_STYLE}/static/${bbox}/` +
    `${width}x${height}@2x?padding=20&access_token=${token}`
  );
}
